version: "3.9"

services:
  {{.AppID}}:
    image: {{.Image}}:{{.ImageVersion}}
    ports:
      {{range $port := .Ports}}- {{$port.No}}:{{if $port.Expose}}:{{$port.No}}
      {{end}}
    {{if .Config}}volumes:
      - {{.Config.Source}}:{{.Config.Target}}:ro{{end}}
    {{if .Depends}}depends_on:
      {{range $dep := .Depends}}- {{$dep}}
      {{end}} 
    {{if .Command}}command: {{.Command}}{{end}
    {{if .Healthcheck}}healthcheck:
      {{.Healthcheck}}{{end}}
    networks:
      - integrations

  # for receivers that scrape this Collector block should be exactly like this
  otel-collector:
    image: otel/opentelemetry-collector-contrib:{{.CollectorVersion}}
    command: ["--config=/conf/collector.yml"]
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    volumes:
      - ./collector.yml:/conf/collector.yml:ro
    networks:
      - integrations

networks:
  integrations:
