apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
data:
  otel-collector-config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 5s
              static_configs:
                - targets: ['0.0.0.0:8888']
            - job_name: "istio"
              scrape_interval: 5s
              metrics_path: "/stats/prometheus"
              kubernetes_sd_configs:
                - role: "pod"
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number]
                  action: replace
                  target_label: __address__
                  regex: ([^:]+);(\d+)
                  replacement: ${1}:${2}
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: kubernetes_namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: kubernetes_pod_name




    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: ingest.lightstep.com:443
        headers:
                "lightstep-access-token": "{LS_ACCESS_TOKEN}"

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [logging,otlp]
