version: '3.9'

services:
  rabbitmq_leader:
    image: rabbitmq:3.9-management
    ports:
        - 5672:5672
        - 15692:15692
        - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 6
    environment: # https://www.rabbitmq.com/configure.html#customise-environment
        - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
        - RABBITMQ_NODENAME=rabbitmq_leader
        - RABBITMQ_DEFAULT_USER=otelu
        - RABBITMQ_DEFAULT_PASS=otelp
    networks:
        - integrations

  rabbitmq_child1:
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
      - RABBITMQ_NODENAME=rabbitmq_child1
      - RABBITMQ_DEFAULT_USER=otelu
      - RABBITMQ_DEFAULT_PASS=otelp
    networks:
        - integrations

  rabbitmq_child2:
    image: rabbitmq:3.9-management
    depends_on:
      rabbitmq_leader:
        condition: service_healthy
    environment:
      - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
      - RABBITMQ_NODENAME=rabbitmq_child2
      - RABBITMQ_DEFAULT_USER=otelu
      - RABBITMQ_DEFAULT_PASS=otelp
    networks:
        - integrations

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    configs:
      - source: collector_conf
        target: /conf/collector.yml
    command: ["--config=/conf/collector.yml"]
    depends_on:
      rabbitmq_leader:
        condition: service_healthy
    networks:
        - integrations

configs:
  collector_conf:
    file: ./collector.yml

networks:
  integrations:
