FROM python:3.10-slim-bullseye

RUN mkdir /app
WORKDIR /app
ADD requirements.txt .
RUN pip install -r requirements.txt

RUN opentelemetry-bootstrap -a install

ADD *.py /app/
CMD ["opentelemetry-instrument", "python", "/app/server.py"]
