FROM python:3.7
RUN pip install protobuf==3.12.2
RUN pip install requests
RUN pip install opentelemetry-instrumentation-requests
RUN pip install opentelemetry-exporter-otlp
RUN pip install opentelemetry-instrumentation

ADD *.py /app/
CMD ["opentelemetry-instrument", "/app/client.py"]
