kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cilium-demo-cluster
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: "10.10.0.0/16"
  serviceSubnet: "10.11.0.0/16"
