build:
	mvn clean package

run: counter updown_counter sum_observer updown_sum_observer value_observer value_recorder

counter:
	java -jar target/metric-test.jar counter

updown_counter:
	java -jar target/metric-test.jar updown_counter

sum_observer:
	java -jar target/metric-test.jar sum_observer

updown_sum_observer:
	java -jar target/metric-test.jar updown_sum_observer

value_observer:
	java -jar target/metric-test.jar value_observer

value_recorder:
	java -jar target/metric-test.jar value_recorder