receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    logLevel: DEBUG
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      exporters: [logging]
    logs:
      receivers: [otlp]
      exporters: [logging]
