machines:
  - name: machine-1
    listenURL: :8080
    peerURL: machine-2.machines.svc.cluster.local:8080
    listenPort: 8080
    advertisePort: 8081
    seed: "true"
  - name: machine-2
    listenURL: :8080
    peerURL: machine-3.machines.svc.cluster.local:8080
    listenPort: 8080
    advertisePort: 8081
    seed: "false"
  - name: machine-3
    listenURL: :8080
    peerURL: machine-1.machines.svc.cluster.local:8080
    listenPort: 8080
    advertisePort: 8081
    seed: "false"
