receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'grafana_metrics'
          scrape_interval: 15s
          scrape_timeout: 5s
          params:
            format: [ 'prometheus' ]
          scheme: 'http'
          tls_config:
            insecure_skip_verify: true
          static_configs:
            - targets: [ 'grafana:3000' ]

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
      "lightstep-access-token": "${LS_ACCESS_TOKEN}"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [ prometheus ]
      processors: [ batch ]
      exporters: [ logging, otlp ]

