apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      prometheus/nginx:
        config:
          scrape_configs:
            - job_name: otel-nginx-eg
              static_configs:
                - targets: ["otel-example:9113"]

    processors:
      batch:

    exporters:
      otlp/public:
        endpoint: ingest.lightstep.com:443
        headers:
          - "lightstep-access-token": "${LS_ACCESS_TOKEN}"

    service:
      pipelines:
        metrics:
          receivers: [prometheus/nginx]
          processors: [batch]
          exporters: [otlp/public]

