FROM python:3-alpine3.15

RUN apk add build-base

RUN mkdir /app
WORKDIR /app
ADD requirements.txt .
RUN pip install -r requirements.txt

RUN opentelemetry-bootstrap -a install

ADD *.py ./
CMD ["opentelemetry-instrument", "/app/server.py", "test"]