version: '3.5'

services:

  etcd0:
    container_name: etcd0
    image: quay.io/coreos/etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0:2379

  mon0:
    container_name: mon0
    image: flaviostutz/ceph-monitor
    pid: host
    environment:
      - CREATE_CLUSTER=true
      - ETCD_URL=http://etcd0:2379
      - PEER_MONITOR_HOSTS=mon1

  mon1:
    container_name: mon1
    image: flaviostutz/ceph-monitor
    pid: host
    environment:
      - ETCD_URL=http://etcd0:2379
      - PEER_MONITOR_HOSTS=mon0

  mgr1:
    container_name: mgr1
    image: flaviostutz/ceph-manager
    pid: host
    ports:
      - 18443:8443 #dashboard https
      - 18003:8003 #restful https
      - 9283:9283 #prometheus
    environment:
      - LOG_LEVEL=0
      - MONITOR_HOSTS=mon0
      - ETCD_URL=http://etcd0:2379

  mgr2:
    container_name: mgr2
    image: flaviostutz/ceph-manager
    pid: host
    ports:
      - 28443:8443 #dashboard https
      - 28003:8003 #restful https
      - 29283:9283 #prometheus
    environment:
      - LOG_LEVEL=0
      - MONITOR_HOSTS=mon0
      - ETCD_URL=http://etcd0:2379

  osd1:
    container_name: osd1
    image: flaviostutz/ceph-osd
    pid: host
    environment:
      - MONITOR_HOSTS=mon0
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://etcd0:2379

  osd2:
    container_name: osd2
    image: flaviostutz/ceph-osd
    pid: host
    environment:
      - MONITOR_HOSTS=mon0
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://etcd0:2379

  osd3:
    container_name: osd3
    image: flaviostutz/ceph-osd
    pid: host
    environment:
      - MONITOR_HOSTS=mon0
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://etcd0:2379

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.56.0
    command: [ "--config=/conf/collector.yml" ]
    ports:
      - 8888:8888
    environment:
      LS_ACCESS_TOKEN: "ezKD2Lo3+5xVULCEAySlqnY1rTBefXN1Dj2CdGLfaAicYA3Fngu52zCIih93+73chQ81I2ax/vpGFJ2a+2+Nh0gWPHOsu0ypKRDNvNuN"
    volumes:
      - ./collector.yml:/conf/collector.yml:rw
    depends_on:
      - mgr1
