version: '3.8'

services:
  
  mon1:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: mon1
    # network_mode: host
    command: mon
    environment:
      - MON_IP=0.0.0.0
      - CEPH_PUBLIC_NETWORK=0.0.0.0/0
    privileged: true
    restart: always
    volumes:
      - ./volumes_data/ceph/ceph:/etc/ceph
      - ./volumes_data/ceph/lib/:/var/lib/ceph/
    networks:
      - cluster-net

  mgr:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: mgr
    # network_mode: host
    command: mgr
    privileged: true
    restart: always
    depends_on:
      - mon1
    ports:
      - 8443:8443
      - 9283:9283
    volumes:
      - ./volumes_data/ceph/ceph:/etc/ceph
      - ./volumes_data/ceph/lib/:/var/lib/ceph
    networks:
      - cluster-net

  osd1:
    pid: host
    image: ceph/daemon
    container_name: osd1
    command: "osd_directory"
    privileged: true
    restart: always
    depends_on:
      - mon1
    volumes:
      - ./volumes_data/ceph/ceph:/etc/ceph
      - ./volumes_data/ceph/lib/:/var/lib/ceph/
      - ./volumes_data/osds/osd1:/var/lib/ceph/osd
    networks:
      - cluster-net

  osd2:
    pid: host
    privileged: true
    restart: always
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: osd2
    command: "osd_directory"
    volumes:
      - ./volumes_data/ceph/ceph:/etc/ceph
      - ./volumes_data/ceph/lib/:/var/lib/ceph/
      - ./volumes_data/osds/osd2:/var/lib/ceph/osd
    depends_on:
      - mon1
    networks:
      - cluster-net

  osd3:
    pid: host
    privileged: true
    restart: always
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: osd3
    command: "osd_directory"
    volumes:
      - ./volumes_data/ceph/ceph:/etc/ceph
      - ./volumes_data/ceph/lib/:/var/lib/ceph/
      - ./volumes_data/osds/osd3:/var/lib/ceph/osd
    depends_on:
      - mon1
    networks:
      - cluster-net

  rgw1:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: osd
    restart: always
    command: "rgw"
    volumes:
      - ./volumes_data/ceph/ceph:/etc/ceph
      - ./volumes_data/ceph/lib/:/var/lib/ceph/
    depends_on:
      - osd1
      - osd2
      - osd3
    networks:
      - cluster-net
    ports:
      - 8080:7480

  mds1:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    container_name: mds1
    command: "mds"
    hostname: "ceph-mds1-host"
    restart: always
    environment:
      CEPHFS_CREATE: 1
    volumes:
      - ./volumes_data/ceph/ceph:/etc/ceph
      - ./volumes_data/ceph/lib/:/var/lib/ceph/
    depends_on:
      - osd1
      - osd2
      - osd3
    networks:
      - cluster-net

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.56.0
    command: [ "--config=/conf/collector.yml" ]
    ports:
      - 8888:8888
    environment:
      LS_ACCESS_TOKEN: "ezKD2Lo3+5xVULCEAySlqnY1rTBefXN1Dj2CdGLfaAicYA3Fngu52zCIih93+73chQ81I2ax/vpGFJ2a+2+Nh0gWPHOsu0ypKRDNvNuN"
    volumes:
      - ./collector.yml:/conf/collector.yml:rw
    depends_on:
      - mon1

networks:
  cluster-net:
    external:
      name: ceph-cluster-net

