version: "3.9"
services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.77.0
    command: [ "--config=/conf/collector.yml" ]
    environment:
      LS_ACCESS_TOKEN: "${LS_ACCESS_TOKEN}"
    volumes:
      - ./collector.yml:/conf/collector.yml:rw
    depends_on:
      vault-server:
        condition: service_started

  vault-server:
    container_name: vault-server
    image: hashicorp/vault:latest
    restart: on-failure
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config:ro
      - vault-file:/vault/file
      - vault-logs:/vault/logs
    command: [ "server","-dev", "-config=/vault/config/policies/prometheus-metrics.hcl", "-log-level=info" ]
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8200/v1/sys/health?standbyok=true" ]
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on:
      consul-server:
        condition: service_healthy

  consul-server:
    container_name: consul-server
    restart: always
    image: hashicorp/consul
    healthcheck:
      test: [ "CMD", "curl", "-X", "GET", "localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 3s
      retries: 10
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/consul-config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/consul-config.json:ro
      - consul-server-data:/consul/data

  consul-worker:
    container_name: consul-worker
    restart: always
    image: hashicorp/consul
    healthcheck:
      test: [ "CMD", "curl", "-X", "GET", "localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 3s
      retries: 10
    ports:
      - "8301:8300"
      - "8401:8400"
      - "8501:8500"
      - "8601:8600"
    command: agent -server -join consul-server -config-file=/consul/config/consul-config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/consul-config.json
      - consul-worker-data:/consul/data
    depends_on:
      consul-server:
        condition: service_healthy

volumes:
  consul-server-data:
    driver: local
  consul-worker-data:
    driver: local
  vault-file:
    driver: local
  vault-logs:
    driver: local
