version: '3.9'
services:
    kong-database:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=kong
          - POSTGRES_PASSWORD=kongpass
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
    kong-db-init:
        image: kong/kong-gateway:3.4.1.1
        command: kong migrations bootstrap
        environment:
          - KONG_DATABASE=postgres
          - KONG_PG_HOST=kong-database
          - KONG_PG_USER=kong
          - KONG_PG_PASSWORD=kongpass
        depends_on:
          kong-database:
            condition: service_started
    kong-gateway:
        image: kong/kong-gateway:3.4.1.1
        environment:
          - KONG_DATABASE=postgres
          - KONG_PG_HOST=kong-database
          - KONG_PG_USER=kong
          - KONG_PG_PASSWORD=kongpass
          - KONG_PROXY_ACCESS_LOG=/dev/stdout
          - KONG_ADMIN_ACCESS_LOG=/dev/stdout
          - KONG_PROXY_ERROR_LOG=/dev/stderr
          - KONG_ADMIN_ERROR_LOG=/dev/stderr
          - KONG_ADMIN_LISTEN=0.0.0.0:8001
          - KONG_ADMIN_GUI_URL=http://localhost:8002
        ports:
          - '8000:8000'
          - '8443:8443'
          - '8001:8001'
          - '8444:8444'
          - '8002:8002'
          - '8445:8445'
          - '8003:8003'
          - '8004:8004'
        depends_on:
          kong-db-init:
            condition: service_completed_successfully
        volumes:
          - ./kong.conf:/etc/kong/kong.conf:rw
    client:
        build: ./app
        container_name: client
        environment:
          - DESTINATION_HOST=kong-gateway
          - COLLECTOR_HOST=otel-collector
        depends_on:
          kong-gateway:
            condition: service_started
          otel-collector:
            condition: service_started
        stop_grace_period: 1s
    otel-collector:
        container_name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.88.0
        command: ["--config=/conf/collector.yml"]
        environment:
            LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
        ports:
          - "4318:4318"
        volumes:
            - ./collector.yml:/conf/collector.yml:rw
