version: '3.9'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
 
  airflow:
    build: .
    environment:
      # -- CORE
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      # -- SCHEDULER
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 10
      # -- ADMIN
      SECURITY__ADMIN_USERNAME: airflow
      SECURITY__ADMIN_PASSWORD: airflow
      # -- DB
      DB__HOST: postgres
      DB__PORT: 5432
      DB__USERNAME: airflow
      DB__PASSWORD: airflow
      DB__NAME: airflow
      # -- METRICS
      AIRFLOW__METRICS__STATSD_ON: True
      AIRFLOW__METRICS__STATSD_HOST: otel-collector
      AIRFLOW__METRICS__STATSD_PORT: 8125
      AIRFLOW__METRICS__STATSD_PREFIX: airflow
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
       - ./dags:/opt/airflow/dags

  otel-collector:
      container_name: otel-collector-airflow
      image: otel/opentelemetry-collector-contrib:latest
      command: ["--config=/conf/collector.yml"]
      environment:
          - LS_ACCESS_TOKEN
      volumes:
          - ./collector.yml:/conf/collector.yml:rw
      networks:
          - integrations

networks:
    integrations:

volumes:
  postgres:
