version: '3.9'

services:
  zookeeper:
    image: zookeeper
    ports:
      - ${ZOO_PORT}:2181
      - 7000:7000
    environment:
      - ALLOW_ANONYMOUS_LOGIN=${ALLOW_ANONYMOUS_LOGIN}
    networks:
      - integrations
    configs:
      - source: zoo_conf
        target: /conf/zoo.cfg
    healthcheck:
      test: echo stat | nc -z zookeeper 2181 || exit -1
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 30s

configs:
  zoo_conf:
    file: ./zoo.cfg

networks:
  integrations:
