apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-otel-collector
spec:
  mode: deployment
  env:
  - name: LS_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: lightstep-secret
        key: lightstep_access_token
        optional: false # require the secret to exist
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-nginx-eg
              static_configs:
                - targets: [nginx-ingress-controller.my-example.svc.cluster.local:9113]
    processors:
      batch:
    exporters:
      logging:
        loglevel: debug
      otlp/public:
        endpoint: ingest.lightstep.com:443
        headers:
          "lightstep-access-token": "${LS_ACCESS_TOKEN}"
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [logging, otlp/public]
