version: '3.7'

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.51.0
    command: ["--config=/conf/collector.yml"]
    ports:
      - 8888:8888
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    volumes:
      - ./collector.yml:/conf/collector.yml:ro
    networks:
      - consul
    depends_on:
      - consul-server

  consul-server:
    image: hashicorp/consul:1.12.2
    container_name: consul-server
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client1:
    image: hashicorp/consul:1.12.2
    container_name: consul-client1
    restart: always
    volumes:
     - ./client1.json:/consul/config/client1.json:ro
     - ./intention-config-entry.json:/intention-config-entry.json
    networks:
      - consul
    ports:
      - "9003:9003"
    environment:
      - PORT=9003
    command: "agent"

  consul-client2:
    image: hashicorp/consul:1.12.2
    container_name: consul-client2
    restart: always
    volumes:
     - ./client2.json:/consul/config/client2.json:ro
    networks:
      - consul
    ports:
      - "9002:9002"
    environment:
      - PORT=9002
      - COUNTING_SERVICE_URL=http://localhost:5000
    command: "agent"

networks:
  consul:
    driver: bridge
