version: '3.7'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.51.0
    command: ["--config=/conf/collector.yml"]
    ports:
      - 8888:8888
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    volumes:
      - ./collector.yml:/conf/collector.yml:ro
    networks:
      - integrations
    depends_on:
      - clickhouse-server

  clickhouse-server:
     image: yandex/clickhouse-server
     container_name: clickhouse-server
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
     networks:
      - integrations
     
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
networks:
    integrations: