version: "3.7"
services:
  mysql:
      container_name: mysql
      image: mysql:5.7
      restart: always
      environment:
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: opentelemetry-tests
      networks:
          - integrations
      stop_grace_period: 1s
  otel-collector:
      container_name: otel-collector
      image: otel/opentelemetry-collector-contrib:0.50.0
      command: ["--config=/conf/collector.yml"]
      environment:
        LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
      networks:
          - integrations
      volumes:
          - ./collector.yml:/conf/collector.yml:rw
networks:
    integrations:
