FROM maven:3.5.2-jdk-8 AS build

RUN apt-get update
RUN apt-get install -y curl
RUN update-ca-certificates -f

WORKDIR /usr/src/app
RUN wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent-all.jar
COPY src ./src
COPY pom-client.xml pom.xml
RUN mvn -f /usr/src/app/pom.xml clean package

FROM openjdk:8

COPY --from=build /usr/src/app/opentelemetry-javaagent-all.jar /app/
COPY --from=build /usr/src/app/target/lightstep-otlp-client.jar /app/

ENTRYPOINT java -jar /app/lightstep-otlp-client.jar \
        com.lightstep.otlp.client.Client
