version: "3"
services:
  opentelemetry-collector-contrib:
    image: otel/opentelemetry-collector-contrib:0.59.0
    command: ["--config=/etc/otel-collector-config.yml"]
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    ports:
      - 4317:4317
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yml
