version: '3.9'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.66.0
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    configs:
      - source: collector_conf
        target: /collector.yml
    command: ["--config=/collector.yml"]
    networks:
      - integrations

  snmpd:
    build: 
      context: ./
      dockerfile: ./Dockerfile_snmp
    configs:
      - source: snmpd_conf
        target: /etc/snmp/snmpd.conf
    networks:
      - integrations
    ports:
      - "161:161"

configs:
  collector_conf:
    file: ./collector.yml
  snmpd_conf:
    file: ./snmpd.conf

networks:
  integrations:
