FROM alpine:3.16 as certs
RUN apk --update add ca-certificates

FROM debian:11

RUN apt update
RUN apt -y install snmpd

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

RUN mkdir /snmp

RUN net-snmp-create-v3-user -ro -a MD5 -A password -x DES -X priv_password collector_user

COPY --chmod=755 ./otelcol-contrib /otelcol-contrib
COPY ./collector.yml /collector.yml

ENTRYPOINT ["snmpd", "-f"]
