receivers:
    otlp:
        protocols:
            grpc:
            http:
    redis:
        endpoint: redis:6379

    mysql:
      username: testuser
      password: testpassword
      endpoint: mysql:3306
    prometheus:
      config:
        scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
              - targets: ['0.0.0.0:8888']
    postgresql:
        endpoint: postgres:5432
        # transport: tcp
        username: testuser
        password: testpassword
        databases:
            - opentelemetry-tests
        tls:
            insecure: true
  
exporters:
    prometheus:
        endpoint: "0.0.0.0:8889"

    logging:
        loglevel: debug

    # configure collector to send data to a local satellite
    # otlp:
    #   endpoint: satellite:8360
    #   insecure: true
    #   headers:
    #     "lightstep-access-token": "<ACCESS TOKEN>"

    # configuring otlp to public satellites
    otlp:
      endpoint: ingest.lightstep.com:443
      headers: 
        "lightstep-access-token": "<ACCESS TOKEN>"
    
      # configure collector to send data to jaeger
    # jaeger:
    #   endpoint: jaeger:6831

processors:
    batch:
  
service:
    telemetry:
        metrics:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [logging, otlp]
        processors: [batch]
      metrics:
        receivers: [mysql, prometheus, redis, postgresql]
        exporters: [logging, otlp]
