version: '3.7'

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.56.0
    command: [ "--config=/conf/collector.yml" ]
    ports:
      - 8888:8888
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    volumes:
      - ./collector.yml:/conf/collector.yml:rw
    depends_on:
      - clickhouse

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    restart: always
    ports:
      - 8001:8001
      - 8123:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - ./config/prom_conf.xml:/etc/clickhouse-server/config.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
