FROM golang as build

# Create appuser.
# See https://stackoverflow.com/a/55757473/12429735
ENV USER=appuser
ENV UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

RUN apt-get update && apt-get install -y ca-certificates

# Build
WORKDIR /go/src/github.com/nslaughter/heyo
RUN git clone --branch main https://github.com/nslaughter/heyo /go/src/github.com/nslaughter/heyo --depth=1
RUN go mod tidy && go mod vendor
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/heyo heyo.go

###############################################################################
# final stage
FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group
USER appuser:appuser

ARG APPLICATION="heyo"
ARG DESCRIPTION="HTTP variable rate load generator"
ARG PACKAGE="nslaughter/heyo"

LABEL org.opencontainers.image.ref.name="${PACKAGE}" \
    org.opencontainers.image.authors="Nathan Slaughter <@nslaughter>" \
    org.opencontainers.image.documentation="https://github.com/${PACKAGE}/README.md" \
    org.opencontainers.image.description="${DESCRIPTION}" \
    org.opencontainers.image.licenses="Apache 2.0" \
    org.opencontainers.image.source="https://github.com/${PACKAGE}"

COPY --from=build /go/bin/${APPLICATION} /heyo
ENTRYPOINT ["/heyo"]
