FROM python:3.7
RUN pip install flask pymongo redis requests sqlalchemy
RUN pip install lightstep
RUN pip install opentelemetry-launcher
RUN pip install git+https://github.com/ocelotl/opentelemetry-python.git@issue_305#subdirectory=opentelemetry-api
RUN pip install git+https://github.com/ocelotl/opentelemetry-python.git@issue_305#subdirectory=opentelemetry-sdk
RUN pip install git+https://github.com/ocelotl/opentelemetry-python.git@issue_305#subdirectory=instrumentation/opentelemetry-instrumentation-opentracing-shim

ADD client.py /app/client.py
CMD ["python", "/app/client.py"]
