FROM python:3.7
RUN pip install flask pymongo redis requests sqlalchemy
RUN pip install opentelemetry-launcher
RUN opentelemetry-bootstrap -a install

ADD server.py /app/server.py
CMD ["opentelemetry-instrument", "/app/server.py"]
