FROM python:3.7

RUN mkdir /app
WORKDIR /app
ADD requirements.txt .
RUN pip install -r requirements.txt

# RUN opentelemetry-bootstrap -a install

ADD server.py /app/server.py
CMD ["opentelemetry-instrument", "python", "/app/server.py"]
