version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:${OTEL_COLLECTOR_VERSION}
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    configs:
      - source: collector_conf
        target: /conf/collector.yml
    depends_on:
      couchbase:
        condition: service_healthy
    volumes:
      - ./statsout:/statsout
    command: ["--config=/conf/collector.yml"]
    networks:
      - integrations

configs:
  collector_conf:
    file: ./collector.yml

      # This provides output for the file receiver
volumes:
  statsout:
    driver: local
