version: '3.9'

services:
  couchbase:
    image: couchbase
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    healthcheck:
      test: curl --fail -u Administrator:password http://localhost:8091/pools || exit 1
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - integrations

networks:
  integrations:
