version: '3.8'

services:
  ad-dc:
    image: mcr.microsoft.com/windows/server:ltsc2022
    container_name: ad-dc
    hostname: ad-dc.example.com
    command: powershell.exe -Command Install-WindowsFeature AD-Domain-Services `
                                  -InstallDns:$true `
                                  -DomainName "example.com" `
                                  -DomainNetbiosName "EXAMPLE" `
                                  -DomainMode "7" `
                                  -ForestMode "7" `
                                  -NoRestart
    environment:
      - SA_PASSWORD=Pa$$w0rd
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "88:88/tcp"
      - "88:88/udp"
      - "135:135/tcp"
      - "139:139/tcp"
      - "389:389/tcp"
      - "389:389/udp"
      - "445:445/tcp"
      - "464:464/tcp"
      - "464:464/udp"
      - "636:636/tcp"
      - "3268:3268/tcp"
      - "3269:3269/tcp"
      - "49152-65535:49152-65535/tcp"
      - "49152-65535:49152-65535/udp"
    restart: always
    networks:
      - integrations

  otel-collector:
      container_name: otel-collector
      image: otel/opentelemetry-collector-contrib:0.74.0
      command: ["--config=/conf/collector.yml"]
      environment:
        LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
      networks:
          - integrations
      volumes:
          - ./collector.yml:/conf/collector.yml:rw

volumes:
  ad-data:

networks:
  integrations:
