version: '3.9'

services:
  otel-collector:
    container_name: otel
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    configs:
      - source: collector_conf
        target: /conf/collector.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--config=/conf/collector.yml"]
  debian:
    image: debian:latest
    tty: True

configs:
  collector_conf:
    file: ./collector.yml
