version: "3.7"
services:
  mongodb:
      container_name: mongodb
      image: mongodb:5.0.7
      restart: always
      environment:
          MONGO_INITDB_DATABASE: admin
          MONGO_INITDB_ROOT_USERNAME: otel
          MONGO_INITDB_ROOT_PASSWORD: testpassword
      networks:
          - integrations
      volumes:
        # seeding scripts
        - ./mongo-entrypoint:/docker-entrypoint-initdb.d
        # named volumes
        - mongodb:/data/db
        - mongoconfig:/data/configdb
      ports:
          - 27017:27017
  otel-collector:
      container_name: otel-collector
      image: otel/opentelemetry-collector-contrib:0.50.0
      command: ["--config=/conf/collector.yml"]
      environment:
        LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
      networks:
          - integrations
      volumes:
          - ./collector.yml:/conf/collector.yml:rw
networks:
    integrations:
