apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: collector
data:
  collector.yml: |-
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: crio
              scrape_interval: 10s
              scheme: http
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              static_configs:
                - targets: ["${K8S_NODE_NAME}:9090"]
    exporters:
      logging:
        loglevel: debug
      otlp/public:
        endpoint: ingest.lightstep.com:443
        headers:
          "lightstep-access-token": "${LS_ACCESS_TOKEN}"
    processors:
      batch:
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [logging, otlp/public]
