apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: collector
data:
  collector.yml: |-
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-kubelet
              scrape_interval: 10s
              scheme: https
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              static_configs:
                - targets: ["${K8S_NODE_NAME}:10250"]
            - job_name: otel-nodes
              scrape_interval: 10s
              static_configs:
                - targets: ["prometheus-node-exporter.kube-system:9100"]
            - job_name: otel-pods
              scrape_interval: 10s
              static_configs:
                - targets: ["kube-state-metrics.kube-system:8080"]
    exporters:
      logging:
        loglevel: debug
      otlp/public:
        endpoint: ingest.lightstep.com:443
        headers:
            "lightstep-access-token": "${LS_ACCESS_TOKEN}"
    processors:
      batch:
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [logging, otlp/public]
