version: '3.9'

services:
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf:/telegraf
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    configs:
      - source: telegraf_conf
        target: /etc/telegraf/telegraf.conf
    depends_on:
      - demosvc
    networks:
      - integrations

  demosvc:
    image: golang:alpine
    working_dir: /app
    volumes:
      - ./app:/app
    command: "go run main.go"
    networks:
      - integrations

configs:
  telegraf_conf:
    file: ./telegraf/telegraf.conf

networks:
  integrations:
