version: "3.2"
services:
  ibmmq-leader:
    image: ibmcom/mq:latest
    hostname: ibmmq-leader
    container_name: 'ibmmq-leader'
    environment:
      - MQ_DEV=true
      - MQ_ADMIN_PASSWORD=password
      - LICENSE=accept
      - MQ_APP_PASSWORD=password
      - MQ_ENABLE_METRICS=true
    volumes:
      - ./mqs.ini:/var/mqm/mqm
    ports:
      - 9157
    networks:
      - integrations
  otel-collector:
      container_name: otel-collect
      hostname: otel-collector
      image: otel/opentelemetry-collector-contrib:0.50.0
      command: ["--config=/conf/config-prometheus.yaml"]
      environment:
        LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
      networks:
          - integrations
      volumes:
          - ./config-prometheus.yaml:/conf/config-prometheus.yaml:rw
networks:
  integrations:
    driver: bridge
