receivers:
  component:
    use_start_time_metric: false
    start_time_metric_regex: '^(.+_)*process_start_time_seconds$'
    config:
exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
      - lightstep-access-token: ${LIGHTSTEP_ACCESS_TOKEN }
service:
  pipelines:
    metrics:
      receivers: [component]
      exporters: [logging, otlp]
