version: "3.7"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
      - 8004:8004
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./conf/hadoop-env.sh:/opt/hadoop-3.2.1/etc/hadoop/hadoop-env.sh
    environment:
      - CLUSTER_NAME=otel
    env_file:
      - ./hadoop.env
    networks:
      - integrations

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - integrations
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    networks:
      - integrations

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - integrations
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - integrations

  otel-collector:
    container_name: otel-collector
    build: .
    command: ["--config=/conf/collector.yml"]
    environment:
        LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    networks:
        - integrations
    volumes:
        - ./collector.yml:/conf/collector.yml:rw
networks:
    integrations:

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
