FROM python:3.7
RUN pip install requests
RUN pip install opentelemetry-launcher
RUN opentelemetry-bootstrap -a install

ADD client.py /app/client.py
CMD ["opentelemetry-instrument", "/app/client.py"]
