FROM python:3.7

RUN mkdir /app
WORKDIR /app
ADD requirements.txt .
RUN pip install -r requirements.txt

# version pinning is here as a workaround for
# a bug in auto instrumentation w/ certificates
# present in 0.16b1
# TODO: remove when 0.17b0 is released
#RUN opentelemetry-bootstrap -a install

ADD client.py /app/client.py
CMD ["opentelemetry-instrument", "/app/client.py"]
