version: '3.9'
services:
    ssh-server:
        container_name: sshserver
        image: lscr.io/linuxserver/openssh-server
        environment:
          - USER_NAME=otelu
          - PASSWORD_ACCESS=true
          - USER_PASSWORD=otelp
        ports:
            - '2222:2222'
        networks:
            - integrations
        stop_grace_period: 1s

    otel-collector:
        build:
          context: .
          args:
            - REPO=nslaughter/opentelemetry-collector-contrib
            - BRANCH=sshcheckreceiver
        command: ["./otelcontribcol", "--config=/conf/collector.yml"]
        environment:
            LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
        networks:
            - integrations
        volumes:
            - ./collector.yml:/conf/collector.yml:r

networks:
    integrations:
