version: "3.7"
services:
    js-ot-shim-server:
        container_name: js-ot-shim-server
#        build: ./nodejs/ot-shim/server
        build: ./server
        networks:
            - demo
        env_file:
            - .env
        environment:
            - OTEL_EXPORTER_OTLP_SPAN_ENDPOINT=https://ingest.lightstep.com:443/api/v2/otel/trace
            - LS_SERVICE_NAME=js-ot-shim-server
        stop_grace_period: 1s
    js-ot-shim-client:
        container_name: js-ot-shim-client
#        build: ./nodejs/ot-shim/client
        build: ./client
        networks:
            - demo
        depends_on:
            - js-ot-shim-server
        env_file:
            - .env
        environment:
            - LS_SERVICE_NAME=js-ot-shim-client
            - OTEL_EXPORTER_OTLP_SPAN_ENDPOINT=https://ingest.lightstep.com:443/api/v2/otel/trace
            - TARGET_URL=http://js-ot-shim-server:8080/ping
        stop_grace_period: 1s
networks:
    demo:
