apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  env:
  - name: LS_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: my-nginx-ingress/lightstep-secret
        key: lightstep-access-token
        optional: false # require the secret to exist
  config: |
    processors:
      batch:
    exporters:
      otlp/public:
        endpoint: ingest.lightstep.com:443
        headers:
          "lightstep-access-token": "${LS_ACCESS_TOKEN}"
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [otlp/public]

