version: '3.5'

services:
  keystore:
    image: elastdocker/elasticsearch:${ELASTIC_VERSION}
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    command: bash /setup/setup-keystore.sh
    user: "0"
    volumes:
        - ./secrets:/secrets
        - ./setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  certs:
    image: elastdocker/elasticsearch:${ELASTIC_VERSION}
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
      - ./secrets:/secrets
      - ./setup/:/setup
