version: '3.9'

services:
  keystore:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    command: bash /setup/setup-keystore.sh
    user: "0"
    volumes:
        - ./secrets:/secrets
        - ./setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
      - ./secrets:/secrets
      - ./setup/:/setup
