name: Run integration tests for go/java/js/python

on:
  pull_request:
    paths:
      - 'go/**'
      - 'java/**'
      - 'nodejs/**'
      - 'browser/**'
      - 'python/**'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  validate_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate config is up-to-date
      run: ./tools/precommit.sh

  test_code:
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Update configuration
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ORG_NAME: ${{ secrets.ORG_NAME }}
        PROJECT_NAME: examples
        API_KEY: ${{ secrets.API_KEY }}
      run: ./tools/update-token.sh

    - name: Pull images
      run: docker-compose pull

    - name: Build images
      run: docker-compose build --parallel

    - name: Run integration test
      run: docker-compose up --exit-code-from integration-test integration-test
