name: Update example containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [
          'go-opentracing-server', 'go-opentracing-client',
          'go-opentelemetry-collector-server', 'go-opentelemetry-collector-client',
          'go-opentelemetry-otlp-server', 'go-opentelemetry-otlp-client',
          'go-launcher-server', 'go-launcher-client',
          'py-opentelemetry-auto-collector-client', 'py-opentelemetry-auto-collector-server',
          'py-opentelemetry-auto-otlp-client', 'py-opentelemetry-auto-otlp-server',
          'py-launcher-client', 'py-launcher-server',
          'demo-client-otlp',
          'py-opentracing-client', 'py-opentracing-server',
          'js-launcher-server', 'js-launcher-client',
          'js-ot-shim-server', 'js-ot-shim-client',
          'java-specialagent-server', 'java-specialagent-client',
          'java-otlp-client', 'java-otlp-server',
          'java-launcher-client', 'java-launcher-server',
          'java-opentracing-server', 'integration-test'
        ]
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set dummy .env file
      run: touch .env

    - name: Build containers
      run: docker-compose build ${{ matrix.component }}

    - name: Push containers
      run: docker-compose push ${{ matrix.component }}
